# Generated by Django 2.0.3 on 2018-03-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptopiccomment',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '管理员'), (2, '会员')], default=1, verbose_name='用户类型'),
        ),
    ]
