# Generated by Django 2.0.3 on 2018-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_ptopiccomment_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDownload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='下载ID')),
                ('user_id', models.IntegerField(verbose_name='下载用户')),
                ('version', models.CharField(max_length=200, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'p_download_record',
            },
        ),
    ]
